In [2]:
import pandas as pd
import numpy as np
from sklearn.svm import SVR
import matplotlib.pyplot as plt
import pickle

In [3]:
modelframe = pd.read_csv("cleaned145dist.csv")

In [4]:
modelframe

,Unnamed: 0,Unnamed: 0.1,time,duration,Holiday,distance,precipIntensity,temperature,humidity,seconds
0,0,2,2018-01-01 08:00:00,51,1,494,0.00,5.84,0.87,28800.0
1,1,3,2018-01-01 08:00:00,47,1,421,0.00,5.84,0.87,28800.0
2,2,4,2018-01-01 08:00:00,59,1,485,0.00,5.84,0.87,28800.0
3,3,5,2018-01-01 08:00:00,98,1,319,0.00,5.84,0.87,28800.0
4,4,6,2018-01-01 08:00:00,40,1,381,0.00,5.84,0.87,28800.0
5,5,7,2018-01-01 08:00:00,30,1,347,0.00,5.84,0.87,28800.0
6,6,8,2018-01-01 08:00:00,36,1,252,0.00,5.84,0.87,28800.0
7,7,9,2018-01-01 08:00:00,11,1,150,0.00,5.84,0.87,28800.0
8,8,10,2018-01-01 08:00:00,21,1,201,0.00,5.84,0.87,28800.0
9,9,11,2018-01-01 08:00:00,42,1,291,0.00,5.84,0.87,28800.0
10,10,12,2018-01-01 08:00:00,58,1,250,0.00,5.84,0.87,28800.0
11,11,13,2018-01-01 08:00:00,44,1,376,0.00,5.84,0.87,28800.0
12,12,14,2018-01-01 08:00:00,58,1,563,0.00,5.84,0.87,28800.0
13,13,15,2018-01-01 08:00:00,24,1,426,0.00,5.84,0.87,28800.0
14,14,16,2018-01-01 08:00:00,11,1,236,0.00,5.84,0.87,28800.0
15,15,17,2018-01-01 08:00:00,11,1,220,0.00,5.84,0.87,28800.0
16,16,18,2018-01-01 08:00:00,7,1,159,0.00,5.84,0.87,28800.0
17,17,19,2018-01-01 08:00:00,25,1,333,0.00,5.84,0.87,28800.0
18,18,20,2018-01-01 08:00:00,29,1,260,0.00,5.84,0.87,28800.0
19,19,21,2018-01-01 08:00:00,67,1,560,0.00,5.84,0.87,28800.0
20,20,22,2018-01-01 08:00:00,43,1,430,0.00,5.84,0.87,28800.0
21,21,23,2018-01-01 08:00:00,56,1,655,0.00,5.84,0.87,28800.0
22,22,24,2018-01-01 08:00:00,50,1,476,0.00,5.84,0.87,28800.0
23,23,25,2018-01-01 08:00:00,42,1,317,0.00,5.84,0.87,28800.0
24,24,26,2018-01-01 08:00:00,49,1,403,0.00,5.84,0.87,28800.0
25,25,27,2018-01-01 08:00:00,51,1,549,0.00,5.84,0.87,28800.0
26,26,28,2018-01-01 08:00:00,36,1,393,0.00,5.84,0.87,28800.0
27,27,29,2018-01-01 08:00:00,43,1,463,0.00,5.84,0.87,28800.0
28,28,30,2018-01-01 08:00:00,40,1,625,0.00,5.84,0.87,28800.0
29,29,31,2018-01-01 08:00:00,73,1,871,0.00,5.84,0.87,28800.0
...,...,...,...,...,...,...,...,...,...,...
3983767,3983767,4102300,2018-12-31 22:00:00,76,0,525,0.02,7.46,0.90,79200.0
3983768,3983768,4102301,2018-12-31 22:00:00,64,0,390,0.02,7.46,0.90,79200.0
3983769,3983769,4102302,2018-12-31 22:00:00,107,0,407,0.02,7.46,0.90,79200.0
3983770,3983770,4102303,2018-12-31 22:00:00,37,0,150,0.02,7.46,0.90,79200.0
3983771,3983771,4102304,2018-12-31 22:00:00,39,0,258,0.02,7.46,0.90,79200.0
3983772,3983772,4102305,2018-12-31 22:00:00,41,0,402,0.02,7.46,0.90,79200.0
3983773,3983773,4102308,2018-12-31 06:00:00,26,0,248,0.01,8.19,0.97,21600.0
3983774,3983774,4102309,2018-12-31 06:00:00,66,0,494,0.01,8.19,0.97,21600.0
3983775,3983775,4102310,2018-12-31 06:00:00,65,0,421,0.01,8.19,0.97,21600.0
3983776,3983776,4102311,2018-12-31 06:00:00,42,0,485,0.01,8.19,0.97,21600.0
3983777,3983777,4102312,2018-12-31 06:00:00,103,0,319,0.01,8.19,0.97,21600.0
3983778,3983778,4102313,2018-12-31 06:00:00,53,0,381,0.01,8.19,0.97,21600.0
3983779,3983779,4102314,2018-12-31 06:00:00,31,0,347,0.01,8.19,0.97,21600.0
3983780,3983780,4102315,2018-12-31 06:00:00,43,0,252,0.01,8.19,0.97,21600.0
3983781,3983781,4102316,2018-12-31 06:00:00,34,0,150,0.01,8.19,0.97,21600.0
3983782,3983782,4102317,2018-12-31 06:00:00,19,0,201,0.01,8.19,0.97,21600.0
3983783,3983783,4102318,2018-12-31 06:00:00,45,0,291,0.01,8.19,0.97,21600.0
3983784,3983784,4102319,2018-12-31 06:00:00,63,0,250,0.01,8.19,0.97,21600.0
3983785,3983785,4102320,2018-12-31 06:00:00,67,0,376,0.01,8.19,0.97,21600.0
3983786,3983786,4102321,2018-12-31 06:00:00,62,0,563,0.01,8.19,0.97,21600.0
3983787,3983787,4102322,2018-12-31 06:00:00,26,0,426,0.01,8.19,0.97,21600.0
3983788,3983788,4102323,2018-12-31 06:00:00,11,0,236,0.01,8.19,0.97,21600.0
3983789,3983789,4102324,2018-12-31 06:00:00,12,0,220,0.01,8.19,0.97,21600.0
3983790,3983790,4102325,2018-12-31 06:00:00,9,0,159,0.01,8.19,0.97,21600.0
3983791,3983791,4102326,2018-12-31 06:00:00,27,0,333,0.01,8.19,0.97,21600.0
3983792,3983792,4102327,2018-12-31 06:00:00,47,0,260,0.01,8.19,0.97,21600.0
3983793,3983793,4102328,2018-12-31 06:00:00,62,0,560,0.01,8.19,0.97,21600.0
3983794,3983794,4102329,2018-12-31 06:00:00,71,0,430,0.01,8.19,0.97,21600.0
3983795,3983795,4102330,2018-12-31 06:00:00,72,0,655,0.01,8.19,0.97,21600.0
3983796,3983796,4102331,2018-12-31 06:00:00,29,0,476,0.01,8.19,0.97,21600.0

In [37]:
clf= pickle.load(open("pickle_model2.pkl", 'rb'))

In [39]:
clf.predict([[0,20000,0.01,8.19,0.97,21600.0]])

array([49.10000001])